### ISSUE TITLE
Test Run

### ISSUE THREAD

**Issue by TheKrakenPriest** [jbloomer/SnipeIT-PythonAPI#1]
Hi jbloomer, Sorry for my english. I'm running your interface on ubuntu 16.04, I installed python 2.7 and i run in the terminal the command **$sudo pip install snipeit** from my download repository.

The snipeit folders were installed in /usr/local/lib/python2.7/dist-packages/snipeit

I tried to open the terminal, run **$python**, and copy the "UsersGetRequestExample.py" code, modifying data from:

server= https://develop.snipeitapp.com/api/v1/users  **<-this is the snipeit development demo** 

token= API TOKEN extract from "metadata" in https://snipe-it.readme.io/v4.1.6/reference#users

**This is the metadata info**
REQUEST HEADERS
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImVmMGVhY2Y4MjAyYzgwZWI2M2JkNmIwZDc0OGYwY2FkYzU2Y2ZlMzgyNzY4ODY0N2EwNmU4ZTBlNmYwZDgwODNjZmMyMzI2YWYyYTZlMTFkIn0.eyJhdWQiOiIxIiwianRpIjoiZWYwZWFjZjgyMDJjODBlYjYzYmQ2YjBkNzQ4ZjBjYWRjNTZjZmUzODI3Njg4NjQ3YTA2ZThlMGU2ZjBkODA4M2NmYzIzMjZhZjJhNmUxMWQiLCJpYXQiOjE0OTMzMzI2MjgsIm5iZiI6MTQ5MzMzMjYyOCwiZXhwIjoxODA4ODY1NDI4LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.NU7ZRIt-d4b0o8uv9ipo1vSWcg1svbmPp47kHErafm9iuK4FjygKd2_4Hp73HKAmjiYcEn3r39pwNh2t9BMFnTXv0KeDGC8zfZ9z7OJN_a59LPoarWBFzCsYETyAm-CeeFnfdj9Cr0ZeGOnnaPuWPYxicwKFeqJI4Hn8nCymcamDGE0u4WOO95ihGOAen4_fqpj-kkBDsvsGhB-cQxeuKdlbvO1yOsKmgQv-kQuxiFMn1zgU7P02mC6XXrbw6jTm7JOaBSbvqSwNtsrSKZkim1jxLsQ4dm36lFmeMkU6hZvNSUnxg8JwbmoxQ_3tZlG3IJh3Sc9ZUi-AEAQ4bbGzi_xNS9fenIdzLDaSiv_esYyNOYXqOuSBk8Yr-720N9OcVjGLnPrV3RtmPisV1aLFgKWLImtlyQgUq3d5LA3QXz8Q_8isvO9Am1u8ri2plbHGJLJ6GRW_mYcBEYMwUozaeXTUe_FUSSO8gpGtO9Hpa5SbERY272_tojyVXpYPaPdUYYmS9CP332jBNESPT8wGwpOM-iddeVo_n82w3dHmDEdp1Brbs3_vKk0AcgvDLsAbd4dZZO-UqddVx6SDb3HLw1Pmw1wGGYHA6w8wWQAiS9kg2xMcz5i75HOULaN3miqYvcPCvHpI2CBfuvdplI8QNm_XzFPmoQRu_5kR8knzla4

When i run the script, this generate a big html code with the "sad panda" ¿this is ok?

¿I need modify the modules in /usr/local/lib/python2.7/dist-packages/snipeit? or only on the examples?

Thaks!!

**Comment by jbloomer** [comment]
I have not tested with the Actualy SnipeIT demo site. I had my own installation I developed with

However to answer your question you should only need to edit the Example files. When a large html is returned, it is a failed API response. 

You should only have to update the server and token variables and then execute the script.

**Comment by jbloomer** [comment]
Also I see you problem

It is the server variable.  Set the server variable to just the base fqdn URL

server= https://develop.snipeitapp.com

The modules in the snipe path will append the URI to the Base URI

**Comment by TheKrakenPriest** [comment]
Hello jbloomer!! I fix the server url = https://develop.snipeitapp.com and it's OK !! I was able to connect and take information from the assets! This integration can be very useful for the snipe-it project! Great!
