### ISSUE TITLE
Examples cite methods that don't exist

### ISSUE THREAD

**Issue by devinnasar** [jbloomer/SnipeIT-PythonAPI#11]
Hello,

I'm trying to execute the Consumables example and getting the following error:

```python3
>>> C = Consumables()
>>> r = C.getID(server, token, "Coffee")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Consumables' object has no attribute 'getID'
```

Can you please explain to me why there's a bunch of example code for methods that don't seem to exist? Thanks!

**Comment by jbloomer** [comment]
Majority of the time when people run into these types of issues it is due to a bad package import call. 

Can you please share your entire script? The error indicates that's the Consumables class was not imported from the snipeit package.

**Comment by devinnasar** [comment]
```python3
L157-DevinNasar:~ devinnasar$ python3
Python 3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from snipeit import Consumables
>>> server = 'https://snipe-it.mydomain.com'
>>> token = 'asbdabsfdpufbasdufbasdfa82348uoabsndfas8d'
>>> C = Consumables()
>>> r = C.getID(server, token, "Coffee")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Consumables' object has no attribute 'getID'
>>>

```

I did a text search of this entire repo and did not find any getID methods in the Consumables class. What's going on here?

**Comment by jbloomer** [comment]
Ok I found the issue. I made a typo when defining the method. It is actually get not getID. I will get that fixed. Thanks for pointing it out

**Comment by devinnasar** [comment]
No problem. I'm onboarding our company's inventory right now and trying to fill in the gaps of the built-in import system. Basically I need these methods if they're available because the UI has people input this stuff by it's name without knowing the ID.

**Comment by jbloomer** [comment]
Yea, I mean I know the system fairly well and I just stood up a fresh clean install of the latest version and I am having issues importing into the licensing part of it. The import just hangs and never processes even if I map the fields. It is finicky how they implemented it.
