### ISSUE TITLE
getDetailsByTag not working 

### ISSUE THREAD

**Issue by spgh-dev** [jbloomer/SnipeIT-PythonAPI#15]
A typo in the AssetTag parameter is generating an exception

**Comment by njtwiseman** [comment]
The definition of 
`    def getDetailsByTag(self, server, token, **AssetTAG**):
        """Get asset details by ID
        
        Arguments:
            server {string} -- Server URI
            token {string} -- Token value to be used for accessing the API
            AssetTAG {string} -- Asset TAG             
        
        Returns:
            [string] -- Asset details from the server, in JSON formatted
        """
        self.uri = '/api/v1/hardware/bytag/' + str(**AssetTAG**)
        self.server = server + self.uri
        headers = {'Authorization': 'Bearer ' + token}
        results = requests.get(self.server, headers=headers)
        return results.content
`

**Comment by nesretep** [comment]
This is still an issue.  I pip installed the latest version today and the mismatched spelling of AssetTAG/AssetTag still exists.

  File "C:\Users\path_goes_here\venv\lib\site-packages\snipeit\Assets.py", line 276, in getDetailsByTag
    self.uri = '/api/v1/hardware/bytag/' + str(AssetTag)
NameError: name 'AssetTag' is not defined

**Comment by rapgro** [comment]
https://github.com/jbloomer/SnipeIT-PythonAPI/pull/21

**Comment by jbloomer** [comment]
Patch just merged
