### ISSUE TITLE
No module named 'Assets'

### ISSUE THREAD

**Issue by quantumzedno** [jbloomer/SnipeIT-PythonAPI#5]
Hi there,

I discovered your library as i am attempting to work with the snipe API via python and it seems like it will avoid me needing to reinvent the wheel so to speak.

To start out i attempted to simply run one of your example scripts with our server/token to see what i will be working with and i get the following error:

C:\Users\<me>\PycharmProjects\Network_Automation\venv\Scripts\python.exe C:/Users/<me>/PycharmProjects/Network_Automation/SnipeAPI.py
Traceback (most recent call last):
  File "C:/Users/<me>/PycharmProjects/Network_Automation/SnipeAPI.py", line 2, in <module>
    from snipeit import Assets
  File "C:\Users\<me>\PycharmProjects\Network_Automation\venv\lib\site-packages\snipeit\__init__.py", line 1, in <module>
    from Assets import Assets
ModuleNotFoundError: No module named 'Assets'

Process finished with exit code 1

**Comment by quantumzedno** [comment]
I managed to sidestep this issue for now by copying the content of Assets.py into my script however I am getting all kinds of JsonDecodeErrors. is this libary working with newer versions of Snipe? I'm running 4.6.4

**Comment by jbloomer** [comment]
I have tested it with as late as 4.4.1. 

It sounds like to me pyCharm may not be installing the snipeit package in your virtual environment. I have not tested this on Windows, but it's Python so it should work. Also there is another Package someone else put out there named snipeit-api that is not mine. It is also a work in progress. I would say make sure PyCharm has the 'snipeit' package installed in your virtual environment. 

![image](https://user-images.githubusercontent.com/6685035/52578516-5ac97b00-2df2-11e9-9d68-f1f929bae943.png)

**Comment by jbloomer** [comment]
All in all it sounds like your errors are package dependency related

**Comment by quantumzedno** [comment]
I'm definitely using your package, I have also tried both version 0.8 and version 0.9, Ive been able to get several similar API libraries installed and working correctly. I'm using python version 3.7 on Pycharm.

I also replicated the issue on a basic linux install that has python 3.4.9, (i ran sudo pip3 install snipeit to install)

from a python console i entered from snipeit import Assets and got the following:

Python 3.4.9 (default, Aug 14 2018, 21:28:57)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from snipeit import Assets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/snipeit/__init__.py", line 1, in <module>
    from Assets import Assets
ImportError: No module named 'Assets'

**Comment by jbloomer** [comment]
OK Could be a Python 3 thing. I will flag it as a bug and look into it

**Comment by jbloomer** [comment]
OK so i figured out the problem. It is a python3 compatibility issue. in __init__.py I need to do 

from .Assets import Assets

This would make it Python 2.7 and Python 3.6 compatible. Let me get that updated recompiled and published to PyPi. Thanks for bringing this to my attention.

**Comment by jbloomer** [comment]
OK new version has been published

You can upgrade with `pip install -U snipeit` or do `pip install snipeit==0.10`

I will close out this request as it has been tested with Python 2.7 and 3.6 and fixes your error

**Comment by quantumzedno** [comment]
Works great, thank you very much!
